"""Generator for the official Threads -> Conversations backfill script.

Emits a standalone, parameterized Python script implementing OpenAI's
official backfill recipe (threads.messages.list -> conversations.create),
hardened with an idempotency journal and a fail-visible content policy.
"""

from . import __version__
from .knowledge import SHUTDOWN_DATE

_SCRIPT = '''#!/usr/bin/env python3
"""Backfill OpenAI Assistants Threads into Conversations before shutdown.

Generated by assistout v{version}. Implements the official migration recipe
(developers.openai.com/api/docs/assistants/migration) with production
properties the docs leave to you: paging, idempotency, and an explicit
unsupported-content policy.

The Assistants API shuts down {shutdown}: after that date threads are
unreadable and this script is useless. Run it BEFORE then.

Usage:
  python backfill_conversations.py thread_id_1 thread_id_2 [...]
  ASSISTOUT_THREAD_IDS="thr_a,thr_b" python backfill_conversations.py

Options:
  --dry-run              Convert and report only; no Conversations created.
  --map PATH             Mapping journal (default: ./backfill_map.jsonl).
                         Already-mapped threads are skipped on re-runs; each
                         success appends one JSON line "thread_id<TAB>conv_id".
  --allow-lossy          Drop unsupported content parts with a warning instead
                         of failing the whole thread. Default is fail-visible:
                         nothing is silently lost.
  --metadata KEY=VAL     Extra metadata for created Conversations (repeatable).
                         legacy_thread_id is always recorded automatically.

Requires: openai>=2.x, stdlib otherwise. Reads OPENAI_API_KEY from env.
"""

import argparse
import json
import os
import sys
from datetime import date, datetime, timezone

try:
    from openai import OpenAI
except ImportError:
    print("pip install openai", file=sys.stderr)
    sys.exit(2)

SHUTDOWN = date({shutdown_year}, {shutdown_month}, {shutdown_day})


def warn(msg):
    print(f"warn: {{msg}}", file=sys.stderr)


def message_to_item(message, allow_lossy=False):
    """Convert one Thread message to a Conversation item per official mapping."""
    content = []
    dropped = []
    for part in message.content:
        if part.type == "text":
            content.append(
                {{
                    "type": "input_text" if message.role == "user" else "output_text",
                    "text": part.text.value,
                }}
            )
        elif part.type == "image_url":
            content.append(
                {{
                    "type": "input_image",
                    "image_url": part.image_url.url,
                    "detail": part.image_url.detail,
                }}
            )
        else:
            # image_file, file_path annotations, code-interpreter outputs...
            dropped.append(part.type)
    if dropped and not allow_lossy:
        raise ValueError(
            f"unsupported content part(s) {{sorted(set(dropped))}} in message "
            f"{{message.id}} - rerun with --allow-lossy to drop them explicitly"
        )
    item = {{"role": message.role, "content": content}}
    return item, sorted(set(dropped))


def load_mapped(map_path):
    mapped = {{}}
    if not os.path.exists(map_path):
        return mapped
    with open(map_path, encoding="utf-8") as fh:
        for line in fh:
            line = line.strip()
            if not line or "\\t" not in line:
                continue
            tid, cid = line.split("\\t", 1)
            mapped[tid] = cid
    return mapped


def record(map_path, thread_id, conversation_id):
    with open(map_path, "a", encoding="utf-8") as fh:
        fh.write(f"{{thread_id}}\\t{{conversation_id}}\\n")


def backfill(client, thread_id, allow_lossy, extra_metadata):
    items = []
    all_dropped = []
    pages = client.beta.threads.messages.list(
        thread_id=thread_id, order="asc"
    ).iter_pages()
    count = 0
    for page in pages:
        for m in page.data:
            item, dropped = message_to_item(m, allow_lossy)
            items.append(item)
            all_dropped.extend(dropped)
            count += 1
    if not items:
        raise ValueError(f"thread {{thread_id}} has no messages")
    metadata = dict(extra_metadata)
    metadata["legacy_thread_id"] = thread_id
    conversation = client.conversations.create(items=items, metadata=metadata)
    return conversation, count, all_dropped


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("thread_ids", nargs="*",
                    help="thread ids; defaults to $ASSISTOUT_THREAD_IDS (comma-separated)")
    ap.add_argument("--dry-run", action="store_true")
    ap.add_argument("--map", default="backfill_map.jsonl", dest="map_path")
    ap.add_argument("--allow-lossy", action="store_true")
    ap.add_argument("--metadata", action="append", default=[], metavar="KEY=VAL")
    args = ap.parse_args()

    raw = args.thread_ids or [
        t.strip() for t in os.environ.get("ASSISTOUT_THREAD_IDS", "").split(",") if t.strip()
    ]
    if not raw:
        ap.error("no thread ids given (argv or $ASSISTOUT_THREAD_IDS)")

    extra_metadata = {{}}
    for kv in args.metadata:
        if "=" not in kv:
            ap.error(f"--metadata expects KEY=VAL, got {{kv!r}}")
        k, v = kv.split("=", 1)
        extra_metadata[k] = v

    today = datetime.now(timezone.utc).date()
    if today >= SHUTDOWN:
        warn(
            f"Assistants API shut down {{SHUTDOWN.isoformat()}}; "
            f"threads.* calls will fail unless data access was extended"
        )

    client = OpenAI()
    mapped = load_mapped(args.map_path)
    failures = 0
    for tid in raw:
        if tid in mapped:
            print(f"skip {{tid}} -> already mapped to {{mapped[tid]}}")
            continue
        try:
            if args.dry_run:
                probe = client.beta.threads.messages.list(
                    thread_id=tid, order="asc", limit=100
                ).iter_pages()
                n = sum(len(p.data) for p in probe)
                print(f"dry-run {{tid}}: {{n}}+ message(s) convertible")
                continue
            conversation, count, dropped = backfill(
                client, tid, args.allow_lossy, extra_metadata
            )
            record(args.map_path, tid, conversation.id)
            note = f", dropped parts: {{sorted(set(dropped))}}" if dropped else ""
            print(f"ok {{tid}} -> {{conversation.id}} ({{count}} items{{note}})")
        except Exception as exc:
            failures += 1
            warn(f"{{tid}} failed: {{exc}}")
    sys.exit(1 if failures else 0)


if __name__ == "__main__":
    main()
'''.format(
    version=__version__,
    shutdown=SHUTDOWN_DATE.isoformat(),
    shutdown_year=SHUTDOWN_DATE.year,
    shutdown_month=SHUTDOWN_DATE.month,
    shutdown_day=SHUTDOWN_DATE.day,
)


def generate_script() -> str:
    """Return the standalone backfill script source."""
    return _SCRIPT
